### ISSUE TITLE
HTML will not be opened

### ISSUE THREAD

**Issue by Freed-Wu** [jeffwright13/pytest-tui#71]
1. change `ptt_files/config.ini` to
```dosini
[TUI]
tui_autolaunch = False

[HTML]
html_autolaunch = True
```

2. `pytest --tui`
3. open `ptt_files/html_report.html`, it is an empty file.

**Comment by jeffwright13** [comment]
Yes, this is a known issue (https://github.com/jeffwright13/pytest-tui/issues/63) and I am working to get it solved, along with some other items. Try running `tuih` after your test run is complete; it should work. As a last resort, you can just run `python pytest_tui/html1.py`.

**Comment by jeffwright13** [comment]
@Freed-Wu : What version of Python are you running in this situation? I have discovered that, if running Python 3.10, there is a problem with `importlib` that prevents the console scripts from running. It works fine with Python 3.9.9.

**Comment by Freed-Wu** [comment]
I use python3.10.

This issue is a repetition of #63. Close.
