### ISSUE TITLE
pytest-tui cannot work with `pytest -n auto`

### ISSUE THREAD

**Issue by Freed-Wu** [jeffwright13/pytest-tui#75]
How about disable pytest-tui when `-n auto` or disable <https://pypi.org/project/pytest-xdist/> when `--tui`?

**Comment by jeffwright13** [comment]
Can you provide a little information on what problem you are seeing when you invoke Pytest with the -n option?

**Comment by Freed-Wu** [comment]
It maybe not a bug. Close before I found more evidence. Thanks!
